Salesforce Dev Demo/force-app/main/default/objects/SAID_Number_Search_Info__c/SAID_Number_Search_Info__c.object-meta.xml
<CustomObject>
    <label>SAID Number Search Info</label>
    <nameField>
        <displayFormat>SAID-{0000000}</displayFormat>
        <label>SAID Number Search Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAID Number Search Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce Dev Demo/force-app/main/default/objects/SAID_Number_Search_Info__c/fields/Birth_Date__c.field-meta.xml
<CustomField>
    <fullName>Birth_Date__c</fullName>
    <description>Birth date extracted from the SA ID</description>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

Salesforce Dev Demo/force-app/main/default/objects/SAID_Number_Search_Info__c/fields/Citizenship__c.field-meta.xml
<CustomField>
    <fullName>Citizenship__c</fullName>
    <description>Citizenship Extracted from the SA ID</description>
    <label>Citizenship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SA Citizen</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce Dev Demo/force-app/main/default/objects/SAID_Number_Search_Info__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Gender Extracted from the SA ID</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce Dev Demo/force-app/main/default/objects/SAID_Number_Search_Info__c/fields/SA_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>SA_ID_Number__c</fullName>
    <description>Store the SA ID Number</description>
    <externalId>true</externalId>
    <inlineHelpText>SA ID Number of user</inlineHelpText>
    <label>SA ID Number</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Salesforce Dev Demo/force-app/main/default/objects/SAID_Number_Search_Info__c/fields/Searches__c.field-meta.xml
<CustomField>
    <fullName>Searches__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of times this SA Id is searched in the system</description>
    <inlineHelpText>Number of times this SA Id is searched in the system</inlineHelpText>
    <label># Searches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Salesforce Dev Demo/force-app/main/default/classes/SAIDControllerTest.cls
/*
* Purpose : Test class for SAIDController 
*			Test class for JSON2ApexHoliday
*
* @author         Pravin Waykar
* @modifiedBy     Pravin Waykar
* @version        1.0
* @created        2023-07-15
* @modified       2023-07-15
*/
@isTest
public class SAIDControllerTest {
    static testMethod void testSAIDSearch(){
        Test.startTest();
        SAID_Number_Search_Info__c  newRecord = new SAID_Number_Search_Info__c();
 		newRecord.Birth_Date__c = date.today().addYears(-30);
        newRecord.Citizenship__c = 'SA Citizen';
        newRecord.Gender__c = 'Male';
        newRecord.SA_ID_Number__c = '2810285800082';
        SAIDController.updateSAIdSearchInfo(newRecord);
        // check if the record is saved
        list<SAID_Number_Search_Info__c> lstSearchRecords = new list<SAID_Number_Search_Info__c>([SELECT id,SA_ID_Number__c,Searches__c FROM SAID_Number_Search_Info__c]);
        system.assertEquals(lstSearchRecords.size(), 1, 'Record is not saved to database');
        
        // test if the #searches are correct
        map<string,Object> mapResults = new map<string,Object>();
        mapResults = SAIDController.updateSAIdSearchInfo(newRecord);
        lstSearchRecords = new list<SAID_Number_Search_Info__c>([SELECT id,SA_ID_Number__c,Searches__c FROM SAID_Number_Search_Info__c]);
        system.assertEquals(lstSearchRecords[0].Searches__c, 2, 'Search Record Information is not updating correctly');
		
        // test that the holidays are returned
        system.assertNotEquals(mapResults.get('lstHolidayWrapper'),null);
        
        // check if the SA ID is different unique search record is created
        newRecord = new SAID_Number_Search_Info__c();
 		newRecord.Birth_Date__c = date.today().addYears(-30);
        newRecord.Citizenship__c = 'SA Citizen';
        newRecord.Gender__c = 'Male';
        newRecord.SA_ID_Number__c = '2810265800086 ';
        SAIDController.updateSAIdSearchInfo(newRecord);
        // check if the record is saved
        lstSearchRecords = new list<SAID_Number_Search_Info__c>([SELECT id,SA_ID_Number__c,Searches__c FROM SAID_Number_Search_Info__c]);
        system.assertEquals(lstSearchRecords.size(), 2, 'Record is not saved to database');
        Test.stopTest();
    }
}